[[redirects]]
  from = "/2"
  to = "https://owo.ecydy.com/link/5gOL5GZ7IpcR1l?clash=1"
  status = 301
  force = false
[[redirects]]
  from = "/3"
  to = "https://my31c.tdwj.net:108/api/v1/client/subscribe?token=d1498a2f7ff3934863a9fcc3fe6e3"
  status = 301
  force = false
[[redirects]]
  from = "/111"
  to = "https://baiducn.top/link/vljf3kuSAlEMT?clash=1"
  status = 301
  force = false
